### ISSUE TITLE
Can we have a 'Now' button, like the 'Today' one?

### ISSUE THREAD

**Issue by af7** [zippyui/react-date-picker#107]
The 'Now' button would also update the Time to now, apart from the Date:

![image](https://cloud.githubusercontent.com/assets/7850073/16469223/7de8863a-3e58-11e6-8549-8b44ea1c5e1d.png)

Also, I would like a different kind of "Now", meaning that it always say "Now" (or something custom) on the DateField. This is useful when you want to perform actions for a range, like From: Today 08:30 To: Now.

Now should be a `value` so that we can evaluate the current time every time we want to use the calendar values.

What do you think?

**Comment by radubrehar** [comment]
We've taken this a step further: you can have your own component as the Footer

eg:

```jsx
import moment from 'moment'

class CustomFooter extends React.Component {
   render() {
       return <div onClick={this.onClick.bind(this)}>
           Now
       </div>
   }

  onClick() {
    //the footer is injected a selectDate prop
     this.props.selectDate({
        dateMoment: moment()
     })
  }
}
CustomFooter.defaultProps = {
  isDatePickerFooter: true //this notifies the calendar it should be used as a footer
}
```
```jsx
<DateField>
  <Calendar>
    <CustomFooter />
  </Calendar>
</DateField>
```

In this way you can basically achieve any functionality you want.

We've released `5.3.14` on npm with support for this. Will also come up with a way to pass a different time to the `Today` button (on which you can already adjust the text, by using `todayButtonText` prop on `Footer`)

**Comment by af7** [comment]
Wow, that was fast! Thanks! Looking forward to your new additions.

**Comment by af7** [comment]
I noticed that the changelog does not mention the new additions, bug fixes, etc. Is there somewhere else where we can see what new exists? Thanks.

**Comment by af7** [comment]
Hi, I tried this but nothing appeared differently:

![image](https://cloud.githubusercontent.com/assets/7850073/16664582/5a8b77a6-4489-11e6-9a4f-323bc0999daf.png)


And I still see this:

![image](https://cloud.githubusercontent.com/assets/7850073/16664598/6d695bb8-4489-11e6-8f0b-cfe4416476e7.png)

**Comment by af7** [comment]
Did I do any mistake on the code above or is this a problem with the library? Thanks!

**Comment by radubrehar** [comment]
If you are using a transition view, you have to nest the footer in the transition view.

**Comment by af7** [comment]
Still, I could not see a "now" button there... I hope you could show an example on the public doc, thanks anyway!
